api_platform:
    title: White Knuckle Leaderboard API
    version: 2.0.0-Pre1
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header
