<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260523014624 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, rules TEXT NOT NULL, is_archived BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, rank_method_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64C19C1CD75392 ON category (rank_method_id)');
        $this->addSql('CREATE TABLE category_subcategory (category_id INT NOT NULL, subcategory_id INT NOT NULL, PRIMARY KEY (category_id, subcategory_id))');
        $this->addSql('CREATE INDEX IDX_BA47E62312469DE2 ON category_subcategory (category_id)');
        $this->addSql('CREATE INDEX IDX_BA47E6235DC6FE57 ON category_subcategory (subcategory_id)');
        $this->addSql('CREATE TABLE climb (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rank BIGINT DEFAULT NULL, score BIGINT DEFAULT NULL, time DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, speed DOUBLE PRECISION DEFAULT NULL, notes TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, is_reviewed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, media_url TEXT NOT NULL, climber_id INT NOT NULL, category_id INT NOT NULL, subcategory_id INT NOT NULL, verifier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5DA9570AA101159 ON climb (climber_id)');
        $this->addSql('CREATE INDEX IDX_5DA9570A12469DE2 ON climb (category_id)');
        $this->addSql('CREATE INDEX IDX_5DA9570A5DC6FE57 ON climb (subcategory_id)');
        $this->addSql('CREATE INDEX IDX_5DA9570A95561DEE ON climb (verifier_id)');
        $this->addSql('CREATE TABLE rank_method (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE subcategory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, discord_id VARCHAR(255) NOT NULL, avatar VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, display_name VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, banned_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1CD75392 FOREIGN KEY (rank_method_id) REFERENCES rank_method (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE category_subcategory ADD CONSTRAINT FK_BA47E62312469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_subcategory ADD CONSTRAINT FK_BA47E6235DC6FE57 FOREIGN KEY (subcategory_id) REFERENCES subcategory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE climb ADD CONSTRAINT FK_5DA9570AA101159 FOREIGN KEY (climber_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE climb ADD CONSTRAINT FK_5DA9570A12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE climb ADD CONSTRAINT FK_5DA9570A5DC6FE57 FOREIGN KEY (subcategory_id) REFERENCES subcategory (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE climb ADD CONSTRAINT FK_5DA9570A95561DEE FOREIGN KEY (verifier_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1CD75392');
        $this->addSql('ALTER TABLE category_subcategory DROP CONSTRAINT FK_BA47E62312469DE2');
        $this->addSql('ALTER TABLE category_subcategory DROP CONSTRAINT FK_BA47E6235DC6FE57');
        $this->addSql('ALTER TABLE climb DROP CONSTRAINT FK_5DA9570AA101159');
        $this->addSql('ALTER TABLE climb DROP CONSTRAINT FK_5DA9570A12469DE2');
        $this->addSql('ALTER TABLE climb DROP CONSTRAINT FK_5DA9570A5DC6FE57');
        $this->addSql('ALTER TABLE climb DROP CONSTRAINT FK_5DA9570A95561DEE');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE category_subcategory');
        $this->addSql('DROP TABLE climb');
        $this->addSql('DROP TABLE rank_method');
        $this->addSql('DROP TABLE subcategory');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
