<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260511224358 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, rules TEXT NOT NULL, is_archived BOOLEAN NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subcategory_id INT NOT NULL, rank_method_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64C19C15DC6FE57 ON category (subcategory_id)');
        $this->addSql('CREATE INDEX IDX_64C19C1CD75392 ON category (rank_method_id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C15DC6FE57 FOREIGN KEY (subcategory_id) REFERENCES subcategory (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1CD75392 FOREIGN KEY (rank_method_id) REFERENCES rank_method (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C15DC6FE57');
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1CD75392');
        $this->addSql('DROP TABLE category');
    }
}
