<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260513003905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE climb (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rank BIGINT DEFAULT NULL, score BIGINT DEFAULT NULL, time DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, speed DOUBLE PRECISION DEFAULT NULL, notes TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, is_reviewed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, media_url TEXT NOT NULL, climber_id INT NOT NULL, category_id INT NOT NULL, subcategory_id INT NOT NULL, verifier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5DA9570AA101159 ON climb (climber_id)');
        $this->addSql('CREATE INDEX IDX_5DA9570A12469DE2 ON climb (category_id)');
        $this->addSql('CREATE INDEX IDX_5DA9570A5DC6FE57 ON climb (subcategory_id)');
        $this->addSql('CREATE INDEX IDX_5DA9570A95561DEE ON climb (verifier_id)');
        $this->addSql('ALTER TABLE climb ADD CONSTRAINT FK_5DA9570AA101159 FOREIGN KEY (climber_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE climb ADD CONSTRAINT FK_5DA9570A12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE climb ADD CONSTRAINT FK_5DA9570A5DC6FE57 FOREIGN KEY (subcategory_id) REFERENCES subcategory (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE climb ADD CONSTRAINT FK_5DA9570A95561DEE FOREIGN KEY (verifier_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE climb DROP CONSTRAINT FK_5DA9570AA101159');
        $this->addSql('ALTER TABLE climb DROP CONSTRAINT FK_5DA9570A12469DE2');
        $this->addSql('ALTER TABLE climb DROP CONSTRAINT FK_5DA9570A5DC6FE57');
        $this->addSql('ALTER TABLE climb DROP CONSTRAINT FK_5DA9570A95561DEE');
        $this->addSql('DROP TABLE climb');
    }
}
